[tool.poetry]
name = "crawler"
version = "0.1.0"
description = "Simple dasgter+"
authors = ["quan.dao <quan.dao@definer-inc.com>"]

[tool.poetry.dependencies]
python = ">=3.10,<3.14"
dagster = "^1.12.3"
dagster-cloud = "^1.12.3"
pandas = "^2.3.3"
snowflake-connector-python = "<4.0.0"
snowflake-sqlalchemy = "^1.7.7"
charset-normalizer = "^3.4.4"

[project.optional-dependencies]
dev = [
    "dagster-dg-cli",
    "dagster-webserver",
    "pytest",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.dg]
directory_type = "project"

[tool.dg.project]
root_module = "crawler"
registry_modules = [
    "crawler.components.*",
]